@baseUrl = http://localhost:3000
@contentType = application/json
@userId = 1
@analysisId = 1

### ==============================
### PREDICT FROM ARTICLE URL
### ==============================
POST {{baseUrl}}/predict
Content-Type: {{contentType}}

{
  "type": "url",
  "url": "https://www.tiktok.com/@hubefananhro/video/7370488646044044551?is_from_webapp=1&sender_device=pc&web_id=7323778420071286273"
}

###

### ==============================
### PREDICT FROM UPLOADED FILE
### (giả lập file .txt / .json đã parse)
### ==============================
POST {{baseUrl}}/predict
Content-Type: {{contentType}}

{
  "type": "file",
  "data": {
    "comments": [
      "bài này ngu vãi",
      "tôi ghét bài này"
    ]
  }
}

###

### ==============================
### INVALID INPUT TYPE (ERROR TEST)
### ==============================
POST {{baseUrl}}/api/predict
Content-Type: {{contentType}}

{
  "type": "abc",
  "data": "something"
}


### =========================
### GET ANALYSIS HISTORY BY USER
### =========================
GET {{baseUrl}}/predict/analysis/user/{{userId}}
Content-Type: application/json

### Delete analysis history
DELETE http://localhost:3000/predict/analysis/5
Content-Type: application/json

{
  "userId": 2
}

###

### =========================
### GET ANALYSIS DETAIL
### =========================
GET {{baseUrl}}/predict/analysis/{{analysisId}}
Content-Type: application/json

### Get Threads comments
GET http://127.0.0.1:8000/thread_comments?url=https://www.threads.com/@loanloanne/post/DQ2IrW8EqQ_?hl=en&limit=50
Accept: application/json

### Get TikTok comments
GET http://127.0.0.1:8000/tiktok_comments?url=https://www.tiktok.com/@plxh.vn/video/7570050309083516191&limit=10
Accept: application/json



