@baseUrl = http://localhost:3000
@contentType = application/json
@userId = 1
@analysisId = 1

### ==============================
### PREDICT FROM ARTICLE URL
### ==============================
POST {{baseUrl}}/predict
Content-Type: {{contentType}}

{
  "type": "url",
  "url": "https://www.reddit.com/r/webdev/comments/1pczxyk/til_why_vite_uses_port_5173/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button"
}

###

### ==============================
### PREDICT FROM UPLOADED FILE
### (giả lập file .txt / .json đã parse)
### ==============================
POST {{baseUrl}}/predict
Content-Type: {{contentType}}

{
  "type": "file",
  "data": {
    "comments": [
      "bài này ngu vãi",
      "tôi ghét bài này"
    ]
  }
}

###

### ==============================
### INVALID INPUT TYPE (ERROR TEST)
### ==============================
POST {{baseUrl}}/api/predict
Content-Type: {{contentType}}

{
  "type": "abc",
  "data": "something"
}


### =========================
### GET ANALYSIS HISTORY BY USER
### =========================
GET {{baseUrl}}/predict/analysis/user/{{userId}}
Content-Type: application/json

###

### =========================
### GET ANALYSIS DETAIL
### =========================
GET {{baseUrl}}/predict/analysis/{{analysisId}}
Content-Type: application/json